name: Multiple inputs as variable(s)

on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment to deploy to'
        type: choice
        options:
        - sandbox
        - development
        - staging
        - production

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          [ "${{ inputs.Environment }}" == "production" ] && is_production=true || is_production=false
          echo "is_production=${is_production}" >> $GITHUB_ENV
          echo $is_production

      - name: Deploy
        shell: bash
        run: |
          # Set envname variable for cloudformation deploy
          [ "${{ env.is_production }}" == true ] && envname=proddy-prod || envname=proddy-dev
          echo $envname

      - name: double brackets
        shell: bash
        run: |
          [[ "${{ inputs.Environment }}" =~ ^(staging|production)$ ]] && snapshot_tag=True || snapshot_tag=False
          echo "snapshot_tag=${snapshot_tag}" >> $GITHUB_ENV
          echo $snapshot_tag
          echo ${snapshot_tag}

      - name: single brackets
        shell: bash
        run: |
          [ "${{ inputs.Environment }}" =~ ^(staging|production)$ ] && snapshot_tag=True || snapshot_tag=False
          echo "snapshot_tag=${snapshot_tag}" >> $GITHUB_ENV
          echo $snapshot_tag
          echo ${snapshot_tag}


      - name: test case syntax
        shell: bash
        run: |
          case "${{ inputs.Environment }}" in staging|production) snapshot_tag=True;; *) snapshot_tag=False;; esac
          echo "snapshot_tag=${snapshot_tag}" >> $GITHUB_ENV
          echo $snapshot_tag
          echo ${snapshot_tag}


