name: Print Output across multiple deploy steps

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - account_name: account1
            account_env: dev
            region: ap-southeast-2
          - account_name: account2
            account_env: prod
            region: ap-southeast-2
    outputs:
      publish-line: ${{ steps.publish.outputs.line }}
    steps:
      - id: publish
        run: |
          VERSION=123
          line="published layer version $VERSION to account ${{ matrix.account_name }}-${{ matrix.account_env }} in region ${{ matrix.region }}"
          echo "line=$line" >> $GITHUB_OUTPUT
          echo "$line"

  summarize:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print deployment summary
        run: |
          echo "Deployment summary:"
          # Use 'jq' only to pluck the outputs, nothing fancy
          echo '${{ toJson(needs.deploy) }}' \
            | jq -r '.[] | .outputs["publish-line"]'
