name: Test Data
on:
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Data
        run: |
          mkdir upload
          echo "test data" >> upload/TEST_data.csv
          cat upload/TEST_data.csv
