name: WTFuonAboot
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Enviroment to deploy to'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  test:
    name: test job
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment variable
        run: |
          [ "${{ inputs.Environment }}" == "production" ] && is_production=true || is_production=false
          echo "is_production=${is_production}" >> $GITHUB_ENV

      - name: echo outputs
        run: |
          echo ${{ env.is_production}}
          echo "${{ inputs.Environment }}"

      - name: run command
        run: |
          [ "${{ env.is_production }}" == true ] && envname=legacy-prod || envname=legacy-dev
          echo "${envname}"
